env:
  es6: true
  node: true
extends: 'eslint:recommended'
parser: 'babel-eslint'
parserOptions:
  sourceType: module
rules:
  no-console: 0
  no-constant-condition: 0
  indent:
    - error
    - 4
    - SwitchCase: 1
  linebreak-style: 0
  quotes:
    - error
    - single
